### ISSUE TITLE
fails on this test image.

### ISSUE THREAD

**Issue by johndpope** [SawanKumarJindal/Vanishing-Point-Detection#1]
![indoor](https://cloud.githubusercontent.com/assets/289994/21621726/3b6e3e4a-d1c8-11e6-88d3-3dd124cb833a.jpg)

<img width="875" alt="screen shot 2017-01-03 at 15 42 28" src="https://cloud.githubusercontent.com/assets/289994/21622339/0bf93180-d1cb-11e6-81f8-e05e71d4e4d6.png">

reference image from here
http://simbaforrest.github.io/code.html

**Comment by SawanKumarJindal** [comment]
Hello John,
     I haven't tested my solution on this set of images. Let me take a look
at it and will provide you with details.

Thanks,
Sawan Kumar Jindal
sawanjindal7@gmail.com
585-350-4178

**Comment by SawanKumarJindal** [comment]
Also, Can you tell me what is the purpose of this test?

Thanks,
Sawan Kumar Jindal

**Comment by johndpope** [comment]
<img width="253" alt="screen shot 2017-01-03 at 20 00 21" src="https://cloud.githubusercontent.com/assets/289994/21628652/10f9a79a-d1ef-11e6-8dad-cc2e9b1137b3.png">
(from here http://simbaforrest.github.io/code.html)   



I'm looking around for an algorithm for real time line / perspective rectangles /  vanishing point for use by iphone camera. I've been digging into white papers - I find the matlab code the cleanest which is how I ended up here.

I know the hough lines is too heavy computationally.
I'm contemplating using a trained algorithm on tensorflow to boost this detection. 

https://github.com/BradLarson/GPUImage2/pull/94/commits/49153c8e457b0820de9048ee1eebe499f1f8bea5

fyi - I'm aware of this code
http://www.cis.pku.edu.cn/vision/vpdetection/

**Comment by SawanKumarJindal** [comment]
There are two things that I would like to mention here:

1: My code uses Hough Transform internally which is computationally heavy
as it has to look into all the degrees of votes but since it was a personal
project, I didn't care much about optimizing it. We can try RANSAC
technique to lower the time.

2: The reason why the image is not working is that the lower section of my
algorithm is specific to a certain set of images. We can make it general by
implementing Expectation Maximization algorithm.

-- Sawan Kumar Jindal

**Comment by johndpope** [comment]
I am looking for run time perspective detection using GMS on mobile.
I think RANSAC / Hough transform are too expensive. 
Check this out  - https://github.com/JiawangBian/GMS-Feature-Matcher

If you're interested to work on something together - let me know.

**Comment by SawanKumarJindal** [comment]
Hello John,
    This looks interesting. I would like to know more about it. Looking
forward to hearing about it.

Thanks,
Sawan
